# Fly.io configuration for FastVLM with memory optimization
app = "fastvlm-screen-observer"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  USE_EXTREME_OPTIMIZATION = "true"
  MAX_MEMORY_GB = "3"
  PORT = "8000"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "60s"
    interval = "30s"
    restart_limit = 0
    timeout = "10s"

# Request 4GB RAM (minimum for 4-bit quantized model)
[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 4096